
import React, { useState, useEffect } from 'react';
import { GameState, Scenario, EvaluationResult, ScoreBreakdown } from '../types';
import { generateScenario, evaluateChoice, getDetailedAnalysis } from '../services/gemini';
import { MapPanel } from './MapPanel';
import { ChatPanel } from './ChatPanel';
import ReactMarkdown from 'react-markdown';
import { 
  AlertTriangle, Clock, Signal, Wind, Trophy, ArrowRight, Loader2, 
  RefreshCw, Backpack, X, Shield, MapPin, Compass, Users, 
  Activity, Thermometer, Moon, Sun, AlertOctagon, EyeOff, SignalLow, 
  MountainSnow, Flame, Info, CheckCircle2
} from 'lucide-react';

// --- Disclaimer Component ---
const DisclaimerModal: React.FC<{ onAccept: () => void }> = ({ onAccept }) => {
  const [canAccept, setCanAccept] = useState(false);
  
  // Force a small delay so they have to look at it
  useEffect(() => {
    const timer = setTimeout(() => setCanAccept(true), 1500);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-red-950/90 backdrop-blur-md">
      <div className="bg-white max-w-lg w-full rounded-3xl shadow-2xl overflow-hidden border-4 border-red-600 animate-in fade-in zoom-in duration-300">
        <div className="bg-red-600 p-6 flex justify-center">
          <AlertOctagon className="w-16 h-16 text-white animate-pulse" />
        </div>
        <div className="p-8 text-center space-y-4">
          <h2 className="text-3xl font-black text-red-600 uppercase tracking-tighter">
            Warning: Simulation Only
          </h2>
          <div className="text-stone-800 font-medium text-lg leading-relaxed space-y-4">
            <p>This application is a <strong>PRACTICE TOOL</strong>.</p>
            <p className="bg-red-50 p-4 rounded-xl border border-red-100">
              It is <strong>NOT</strong> intended to be educational or provide real medical/survival advice. 
              The scenarios are generated by AI and may be inaccurate or hallucinated.
            </p>
            <p>Do <strong>NOT</strong> rely on this app for real-world safety. 
              Always follow local authorities and professional training.</p>
            <p className="text-xs text-stone-500 uppercase font-bold tracking-widest mt-6">
              We take no responsibility for your actions.
            </p>
          </div>
          <button
            onClick={onAccept}
            disabled={!canAccept}
            className="w-full py-4 mt-6 bg-red-600 hover:bg-red-700 text-white font-bold text-xl rounded-xl shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {canAccept ? "I UNDERSTAND & AGREE" : "Reading..."}
          </button>
        </div>
      </div>
    </div>
  );
};

// --- Score Board Sidebar ---
const ScoreBoard: React.FC<{ scores: ScoreBreakdown, theme: string }> = ({ scores, theme }) => {
  const isDark = theme === 'night';
  const textColor = isDark ? 'text-stone-200' : 'text-stone-700';
  const labelColor = isDark ? 'text-stone-500' : 'text-stone-400';
  const bgBar = isDark ? 'bg-stone-800' : 'bg-stone-200';

  const ScoreRow = ({ icon: Icon, label, value }: { icon: any, label: string, value: number }) => (
    <div className="mb-4">
      <div className="flex justify-between items-center mb-1">
        <div className="flex items-center gap-2">
          <Icon className={`w-4 h-4 ${value < 50 ? 'text-red-500' : isDark ? 'text-nature-400' : 'text-nature-600'}`} />
          <span className={`text-xs font-bold uppercase tracking-wider ${labelColor}`}>{label}</span>
        </div>
        <span className={`text-sm font-mono font-bold ${textColor}`}>{value}</span>
      </div>
      <div className={`w-full h-1.5 ${bgBar} rounded-full overflow-hidden`}>
        <div 
          className={`h-full transition-all duration-500 ${value < 40 ? 'bg-red-500' : value < 70 ? 'bg-yellow-500' : 'bg-nature-500'}`} 
          style={{ width: `${Math.max(0, Math.min(100, value))}%` }}
        />
      </div>
    </div>
  );

  return (
    <div className={`p-5 rounded-2xl border ${isDark ? 'bg-stone-900/80 border-stone-800' : 'bg-white/80 border-stone-200'} backdrop-blur-md shadow-sm`}>
      <h3 className={`text-sm font-black uppercase mb-4 ${isDark ? 'text-stone-300' : 'text-stone-800'}`}>Performance Metrics</h3>
      <ScoreRow icon={Compass} label="Navigation" value={scores.navigation} />
      <ScoreRow icon={Wind} label="Weather Judgement" value={scores.weather} />
      <ScoreRow icon={Users} label="Group Safety" value={scores.groupSafety} />
      <ScoreRow icon={Shield} label="Risk Awareness" value={scores.riskManagement} />
      <ScoreRow icon={Clock} label="Timing" value={scores.timing} />
    </div>
  );
};

const InventoryModal: React.FC<{ 
  scenario: Scenario, 
  onClose: () => void 
}> = ({ scenario, onClose }) => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden border border-stone-200">
        <div className="bg-stone-100 p-4 flex justify-between items-center border-b border-stone-200">
          <div className="flex items-center gap-2 text-stone-800">
            <Backpack className="w-5 h-5 text-nature-600" />
            <h3 className="font-bold">Equipment Check</h3>
          </div>
          <button onClick={onClose} className="p-1 hover:bg-stone-200 rounded-full transition-colors">
            <X className="w-5 h-5 text-stone-500" />
          </button>
        </div>
        <div className="p-6 space-y-6 max-h-[70vh] overflow-y-auto">
          {Object.entries(scenario.inventory).map(([key, items]) => (
             <div key={key}>
                <h4 className="text-xs font-bold uppercase text-stone-500 tracking-wider mb-2">
                  {key.replace(/([A-Z])/g, ' $1').trim()}
                </h4>
                <div className="flex flex-wrap gap-2">
                  {(items as string[]).length > 0 ? (
                    (items as string[]).map((item, i) => (
                      <span key={i} className="px-3 py-1.5 bg-stone-50 border border-stone-200 rounded-lg text-sm text-stone-700">
                        {item}
                      </span>
                    ))
                  ) : <span className="text-sm text-stone-400 italic">Empty...</span>}
                </div>
             </div>
          ))}
        </div>
      </div>
    </div>
  );
};

// --- Main Interface ---
export const GameInterface: React.FC = () => {
  const [gameState, setGameState] = useState<GameState>({
    phase: 'disclaimer',
    currentScenario: null,
    history: [],
    scores: { navigation: 50, weather: 50, groupSafety: 50, riskManagement: 50, timing: 50 },
    totalTurns: 0,
  });

  // Menu Inputs
  const [difficulty, setDifficulty] = useState('Moderate');
  const [terrain, setTerrain] = useState('Mountain Forest');
  const [gameMode, setGameMode] = useState<'Standard' | 'Night Ops' | 'Heat Wave' | 'Tiny Mistakes'>('Standard');
  const [customInput, setCustomInput] = useState('');
  
  // UI State
  const [loading, setLoading] = useState(false);
  const [loadingText, setLoadingText] = useState('Loading...');
  const [analysis, setAnalysis] = useState<string>('');
  const [customAction, setCustomAction] = useState('');
  const [showInventory, setShowInventory] = useState(false);

  // Theme Helpers
  const isNight = gameState.currentScenario?.theme === 'night';
  const isHeat = gameState.currentScenario?.theme === 'heat';
  
  const bgClass = isNight ? 'bg-stone-900' : isHeat ? 'bg-orange-50' : 'bg-[#f5f5f4]';
  const textClass = isNight ? 'text-stone-100' : 'text-stone-900';
  const cardClass = isNight ? 'bg-stone-800 border-stone-700' : 'bg-white border-stone-200';

  const startGame = async () => {
    setLoading(true);
    setLoadingText(`Initializing ${gameMode} Protocol...`);
    try {
      const scenario = await generateScenario(difficulty, terrain, gameMode, customInput);
      setGameState({
        phase: 'playing',
        currentScenario: scenario,
        history: [],
        scores: { navigation: 50, weather: 50, groupSafety: 50, riskManagement: 50, timing: 50 },
        totalTurns: 0
      });
      setCustomAction('');
    } finally {
      setLoading(false);
    }
  };

  const processDecision = async (actionText: string) => {
    if (!gameState.currentScenario) return;

    setLoading(true);
    setLoadingText('Calculating risks & outcomes...');
    
    try {
      const result = await evaluateChoice(
        gameState.currentScenario, 
        actionText, 
        gameState.scores,
        gameState.history
      );

      // Helper to clamp scores 0-100
      const clamp = (curr: number, delta: number = 0) => Math.max(0, Math.min(100, curr + delta));

      const newScores: ScoreBreakdown = {
        navigation: clamp(gameState.scores.navigation, result.scoreDeltas.navigation),
        weather: clamp(gameState.scores.weather, result.scoreDeltas.weather),
        groupSafety: clamp(gameState.scores.groupSafety, result.scoreDeltas.groupSafety),
        riskManagement: clamp(gameState.scores.riskManagement, result.scoreDeltas.riskManagement),
        timing: clamp(gameState.scores.timing, result.scoreDeltas.timing),
      };

      const newHistoryItem = {
        scenarioDescription: gameState.currentScenario.description,
        choice: actionText,
        outcome: result.outcomeText,
        scoreDeltas: result.scoreDeltas
      };

      if (result.isGameOver) {
        setGameState(prev => ({
          ...prev,
          phase: 'summary',
          scores: newScores,
          gameOverReason: result.gameOverReason,
          history: [...prev.history, newHistoryItem]
        }));
      } else {
        setGameState(prev => ({
          ...prev,
          scores: newScores,
          totalTurns: prev.totalTurns + 1,
          history: [...prev.history, newHistoryItem],
          currentScenario: {
            ...prev.currentScenario!,
            description: result.nextScenarioPart?.description || prev.currentScenario!.description,
            choices: result.nextScenarioPart?.choices || [],
            turnCount: prev.currentScenario!.turnCount + 1
          }
        }));
        setCustomAction('');
      }
    } finally {
      setLoading(false);
    }
  };

  const requestDeepAnalysis = async () => {
      setLoading(true);
      setLoadingText("Running Gemini Thinking analysis on your performance...");
      const report = await getDetailedAnalysis(gameState.history, gameState.scores);
      setAnalysis(report);
      setLoading(false);
  };

  // Helper for hazards
  const getHazards = (env: Scenario['environment'], location: Scenario['location']) => {
    const hazards = [];
    const temp = env.temperature.toLowerCase();
    
    if (temp.includes('95') || temp.includes('100') || temp.includes('35°c') || temp.includes('hot')) {
        hazards.push({ icon: Flame, color: 'text-orange-500', label: 'Extreme Heat' });
    }
    if (temp.includes('freezing') || temp.includes('cold') || temp.includes('-')) {
        hazards.push({ icon: Thermometer, color: 'text-blue-500', label: 'Freezing' });
    }
    if (env.visibility === 'Poor') {
        hazards.push({ icon: EyeOff, color: 'text-stone-500', label: 'Low Vis' });
    }
    if (env.signalStrength === 'None' || env.signalStrength === 'Weak') {
        hazards.push({ icon: SignalLow, color: 'text-red-500', label: 'Weak/No Signal' });
    }
    if (location.terrainType.toLowerCase().includes('cliff') || location.terrainType.toLowerCase().includes('steep')) {
        hazards.push({ icon: MountainSnow, color: 'text-stone-700', label: 'Fall Risk' });
    }
    return hazards;
  };

  const tooltips = {
    'Standard': "Balanced experience. Good for learning the basics of survival decision making.",
    'Night Ops': "Limited visibility and falling temperatures. Tests your ability to navigate without clear landmarks.",
    'Heat Wave': "High temperature conditions. Managing hydration and exertion is critical to prevent heat exhaustion.",
    'Tiny Mistakes': "Starts with a common error (e.g., forgot headlamp). Focuses on error recovery and preventing compounding mistakes."
  };

  if (gameState.phase === 'disclaimer') {
    return <DisclaimerModal onAccept={() => setGameState(prev => ({ ...prev, phase: 'menu' }))} />;
  }

  if (gameState.phase === 'menu') {
    return (
      <div className="min-h-screen bg-stone-100 flex items-center justify-center p-4">
        <div className="max-w-2xl w-full bg-white rounded-3xl shadow-xl p-8 border border-stone-100">
          <div className="text-center mb-8">
            <div className="inline-flex p-4 bg-nature-50 rounded-2xl mb-4 shadow-sm">
              <Trophy className="w-10 h-10 text-nature-600" />
            </div>
            <h1 className="text-3xl font-black text-stone-900 tracking-tight">Backcountry Safety</h1>
            <p className="text-stone-500 mt-2 font-medium">Training Simulator v2.0</p>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
             <div className="space-y-6">
                <div>
                   <label className="text-xs font-bold text-stone-400 uppercase tracking-wider mb-2 block">Game Mode</label>
                   <div className="space-y-2">
                      {['Standard', 'Night Ops', 'Heat Wave', 'Tiny Mistakes'].map(m => (
                          <div key={m} className="group relative">
                            <button 
                              onClick={() => setGameMode(m as any)}
                              className={`w-full py-3 px-4 text-left rounded-xl border text-sm font-semibold transition-all ${
                                  gameMode === m 
                                  ? 'bg-stone-800 text-white border-stone-800 shadow-md ring-2 ring-stone-300 ring-offset-2' 
                                  : 'bg-white text-stone-600 border-stone-200 hover:bg-stone-50'
                              }`}
                            >
                              <div className="flex items-center justify-between">
                                  <div className="flex items-center gap-2">
                                     {m}
                                  </div>
                                  {m === 'Night Ops' && <Moon className="w-4 h-4" />}
                                  {m === 'Heat Wave' && <Sun className="w-4 h-4" />}
                                  {m === 'Tiny Mistakes' && <AlertTriangle className="w-4 h-4" />}
                              </div>
                            </button>
                            {/* Tooltip */}
                            <div className="absolute right-[-10px] top-1/2 -translate-y-1/2 translate-x-full hidden group-hover:block z-10 w-48 bg-stone-900 text-white text-xs p-2 rounded-lg shadow-lg">
                               {tooltips[m as keyof typeof tooltips]}
                               <div className="absolute left-0 top-1/2 -translate-x-1/2 -translate-y-1/2 border-8 border-transparent border-r-stone-900"></div>
                            </div>
                            <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none md:hidden text-stone-300">
                                <Info className="w-3 h-3" />
                            </div>
                          </div>
                      ))}
                   </div>
                </div>
                <div>
                  <label className="text-xs font-bold text-stone-400 uppercase tracking-wider mb-2 block">Difficulty</label>
                  <div className="flex gap-2">
                     {['Easy', 'Moderate', 'Hard'].map(d => (
                       <button
                         key={d}
                         onClick={() => setDifficulty(d)}
                         className={`flex-1 py-2 text-xs font-bold uppercase rounded-lg border transition-colors ${
                           difficulty === d 
                             ? 'bg-nature-600 text-white border-nature-600' 
                             : 'bg-white text-stone-500 border-stone-200 hover:bg-stone-50'
                         }`}
                       >
                         {d}
                       </button>
                     ))}
                  </div>
                </div>
             </div>

             <div className="space-y-6">
                <div>
                    <label className="text-xs font-bold text-stone-400 uppercase tracking-wider mb-2 block">Environment</label>
                    <select 
                      value={terrain}
                      onChange={(e) => setTerrain(e.target.value)}
                      className="w-full p-3 bg-stone-50 border border-stone-200 rounded-xl text-stone-700 outline-none focus:border-nature-500 font-medium"
                    >
                      <option>Mountain Forest</option>
                      <option>High Desert</option>
                      <option>Alpine Ridge</option>
                      <option>Coastal Track</option>
                      <option>Dense Jungle</option>
                      <option>Snowy Tundra</option>
                    </select>
                </div>
                <div>
                  <label className="text-xs font-bold text-stone-400 uppercase tracking-wider mb-2 block">Custom Notes</label>
                  <textarea
                    value={customInput}
                    onChange={(e) => setCustomInput(e.target.value)}
                    placeholder="E.g. 'I want to practice snake bites' or 'Lost with no signal'"
                    className="w-full p-3 bg-stone-50 border border-stone-200 rounded-xl text-sm text-stone-700 placeholder-stone-400 outline-none focus:border-nature-500 resize-none h-32"
                  />
                </div>
             </div>
          </div>

          <button
            onClick={startGame}
            disabled={loading}
            className="w-full py-5 bg-nature-600 hover:bg-nature-700 text-white rounded-2xl font-bold text-lg shadow-xl shadow-nature-200 hover:shadow-2xl hover:scale-[1.01] transition-all flex justify-center items-center gap-3 mt-8"
          >
            {loading ? <Loader2 className="animate-spin w-6 h-6" /> : (
              <>
                Initialize Simulation
                <ArrowRight className="w-6 h-6" />
              </>
            )}
          </button>
        </div>
      </div>
    );
  }

  // --- Summary View ---
  if (gameState.phase === 'summary') {
    return (
      <div className="min-h-screen bg-stone-100 p-4 md:p-8 overflow-auto">
        <div className="max-w-4xl mx-auto space-y-6">
          <div className="bg-white rounded-3xl shadow-xl p-8 border border-stone-200">
             <div className="text-center border-b border-stone-100 pb-8 mb-8">
                <div className="inline-flex items-center justify-center w-20 h-20 bg-stone-100 rounded-full mb-4">
                  <Shield className="w-10 h-10 text-stone-800" />
                </div>
                <h2 className="text-4xl font-black text-stone-900 mb-2">Simulation Ended</h2>
                <p className="text-xl text-stone-500 font-medium">{gameState.gameOverReason}</p>
             </div>

             <div className="grid md:grid-cols-2 gap-8 mb-8">
                <ScoreBoard scores={gameState.scores} theme="normal" />
                
                <div className="flex flex-col justify-center space-y-4">
                   <div className="p-6 bg-nature-50 rounded-2xl border border-nature-100">
                      <h3 className="font-bold text-nature-800 mb-2">Mission Highlights</h3>
                      <p className="text-sm text-nature-700">
                        You survived {gameState.totalTurns} turns. 
                        Navigation integrity: {gameState.scores.navigation}%. 
                        Group safety: {gameState.scores.groupSafety}%.
                      </p>
                   </div>
                   {!analysis ? (
                       <button 
                         onClick={requestDeepAnalysis}
                         disabled={loading}
                         className="w-full py-4 bg-stone-900 text-white rounded-xl font-bold shadow-lg flex items-center justify-center gap-2 hover:bg-stone-800 transition-all"
                       >
                         {loading ? <Loader2 className="animate-spin w-5 h-5" /> : <Activity className="w-5 h-5" />}
                         What Could I Have Done Differently?
                       </button>
                   ) : (
                     <div className="text-center text-sm text-stone-400 font-medium">Analysis Complete</div>
                   )}
                </div>
             </div>
             
             {analysis && (
               <div className="prose prose-stone max-w-none bg-stone-50 p-6 rounded-2xl border border-stone-200 animate-in fade-in slide-in-from-bottom-4">
                  <h3 className="text-lg font-bold text-stone-800 mb-4 flex items-center gap-2">
                    <Users className="w-5 h-5 text-nature-600" />
                    Coach's Debrief
                  </h3>
                   <ReactMarkdown className="text-sm text-stone-600 leading-relaxed">
                     {analysis}
                   </ReactMarkdown>
               </div>
             )}

             <div className="mt-8 flex justify-end">
                <button
                  onClick={() => setGameState(prev => ({ ...prev, phase: 'menu' }))}
                  className="flex items-center gap-2 px-8 py-4 bg-white border border-stone-200 text-stone-700 hover:bg-stone-50 rounded-2xl transition-all shadow-sm font-bold"
                >
                  <RefreshCw className="w-5 h-5" />
                  Return to Menu
                </button>
             </div>
          </div>
        </div>
      </div>
    );
  }

  // --- Playing Phase ---
  const hazards = gameState.currentScenario ? getHazards(gameState.currentScenario.environment, gameState.currentScenario.location) : [];
  const progressPercent = gameState.currentScenario ? Math.min(100, (gameState.totalTurns / gameState.currentScenario.estimatedDuration) * 100) : 0;

  return (
    <div className={`h-screen flex flex-col md:flex-row ${bgClass} overflow-hidden relative transition-colors duration-500`}>
      {showInventory && gameState.currentScenario && (
        <InventoryModal 
          scenario={gameState.currentScenario} 
          onClose={() => setShowInventory(false)} 
        />
      )}

      {/* Main Game Area */}
      <div className="flex-1 flex flex-col h-full overflow-hidden shadow-2xl z-10 relative">
        
        {/* Persistent Status Bar */}
        <div className={`${isNight ? 'bg-stone-900 border-stone-800 text-stone-300' : 'bg-white border-stone-200 text-stone-600'} border-b px-4 py-3 flex items-center justify-between transition-colors duration-500`}>
           <div className="flex items-center gap-6">
              <div className="flex gap-4 text-xs font-bold uppercase tracking-wider">
                  <span className="flex items-center gap-1.5"><Clock className="w-3.5 h-3.5" /> {gameState.currentScenario?.environment.timeOfDay}</span>
                  <span className="flex items-center gap-1.5"><Thermometer className="w-3.5 h-3.5" /> {gameState.currentScenario?.environment.temperature}</span>
                  <span className="flex items-center gap-1.5"><Wind className="w-3.5 h-3.5" /> {gameState.currentScenario?.environment.weather}</span>
              </div>
              
              {/* Hazard Icons */}
              {hazards.length > 0 && (
                <div className="hidden md:flex gap-3 pl-4 border-l border-stone-200/20">
                    {hazards.map((h, i) => (
                        <div key={i} className={`flex items-center gap-1 text-[10px] font-bold uppercase ${h.color}`} title={h.label}>
                            <h.icon className="w-4 h-4" />
                            <span className="hidden lg:inline">{h.label}</span>
                        </div>
                    ))}
                </div>
              )}
           </div>
           
           <button 
             onClick={() => setShowInventory(true)}
             className="flex items-center gap-1 text-xs font-bold uppercase tracking-wider hover:text-nature-500 transition-colors"
           >
              <Backpack className="w-3.5 h-3.5" /> Pack
           </button>
        </div>
        
        {/* Mobile Hazard Bar */}
        {hazards.length > 0 && (
            <div className={`md:hidden px-4 py-2 border-b flex gap-4 overflow-x-auto ${isNight ? 'bg-stone-800 border-stone-700' : 'bg-stone-50 border-stone-200'}`}>
                {hazards.map((h, i) => (
                    <div key={i} className={`flex items-center gap-1.5 text-[10px] font-bold uppercase shrink-0 ${h.color}`}>
                        <h.icon className="w-3.5 h-3.5" />
                        <span>{h.label}</span>
                    </div>
                ))}
            </div>
        )}

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto p-4 md:p-6 space-y-6">
          
          {/* Progress Bar */}
          <div className="w-full bg-stone-200/50 rounded-full h-1.5 overflow-hidden">
             <div className="bg-nature-500 h-full transition-all duration-700" style={{ width: `${progressPercent}%` }}></div>
          </div>
          <div className="flex justify-between text-[10px] uppercase font-bold text-stone-400 tracking-wider -mt-4">
             <span>Start</span>
             <span>Survival Progress</span>
             <span>Goal</span>
          </div>

          {/* Situation Card */}
          <div className={`${cardClass} p-6 md:p-8 rounded-2xl shadow-sm border relative overflow-hidden transition-colors duration-500`}>
             <div className={`absolute top-0 left-0 w-1.5 h-full ${isNight ? 'bg-indigo-500' : 'bg-amber-500'}`}></div>
             <div className="flex gap-5 items-start relative z-10">
               <div className={`p-3 rounded-xl shrink-0 ${isNight ? 'bg-stone-700' : 'bg-amber-50'}`}>
                 {isNight ? <Moon className="w-8 h-8 text-indigo-300" /> : <AlertTriangle className="w-8 h-8 text-amber-600" />}
               </div>
               <div className="flex-1">
                 <h2 className={`font-black text-xl mb-3 ${textClass}`}>{gameState.currentScenario?.title}</h2>
                 <p className={`${isNight ? 'text-stone-300' : 'text-stone-700'} leading-relaxed text-base md:text-lg`}>
                   {gameState.currentScenario?.description}
                 </p>
                 
                 {gameState.history.length > 0 && (
                   <div className={`mt-6 p-4 rounded-xl border ${isNight ? 'bg-stone-900 border-stone-700' : 'bg-stone-50 border-stone-200'} text-sm flex gap-3`}>
                      <div className="w-1 bg-stone-400 rounded-full"></div>
                      <div>
                        <span className="block text-xs font-bold text-stone-400 uppercase tracking-wide mb-1">Previous Result</span>
                        <span className={`italic ${isNight ? 'text-stone-300' : 'text-stone-600'}`}>"{gameState.history[gameState.history.length-1].outcome}"</span>
                      </div>
                   </div>
                 )}
               </div>
             </div>
          </div>

          {/* Choices */}
          <div className="grid gap-3">
             {loading ? (
               <div className={`py-12 rounded-2xl border flex flex-col items-center justify-center gap-4 animate-pulse ${isNight ? 'bg-stone-800/50 border-stone-700' : 'bg-white/50 border-stone-200'}`}>
                 <Loader2 className={`w-8 h-8 animate-spin ${isNight ? 'text-stone-400' : 'text-nature-600'}`} />
                 <p className={`font-medium ${isNight ? 'text-stone-400' : 'text-stone-500'}`}>{loadingText}</p>
               </div>
             ) : (
               <>
                 {gameState.currentScenario?.choices.map(choice => (
                   <button
                     key={choice.id}
                     onClick={() => processDecision(choice.text)}
                     className={`group text-left p-5 rounded-2xl border transition-all shadow-sm hover:shadow-md flex items-center justify-between
                        ${isNight 
                          ? 'bg-stone-800 border-stone-700 hover:bg-stone-700 text-stone-200' 
                          : 'bg-white border-stone-200 hover:bg-nature-50 text-stone-700 hover:text-nature-900'
                        }
                     `}
                   >
                     <span className="font-medium text-lg">{choice.text}</span>
                     <div className={`p-2 rounded-full transition-colors ${isNight ? 'bg-stone-700 group-hover:bg-stone-600' : 'bg-stone-50 group-hover:bg-nature-100'}`}>
                       <ArrowRight className={`w-5 h-5 ${isNight ? 'text-stone-400' : 'text-stone-400 group-hover:text-nature-600'}`} />
                     </div>
                   </button>
                 ))}
                 
                 {/* Custom Input */}
                 <div className="mt-4 pt-4 border-t border-stone-200/20">
                    <div className="flex gap-2">
                        <input 
                            type="text" 
                            value={customAction}
                            onChange={(e) => setCustomAction(e.target.value)}
                            onKeyDown={(e) => e.key === 'Enter' && customAction.trim() && processDecision(customAction)}
                            placeholder="Improvise an action..."
                            className={`flex-1 p-4 rounded-xl border outline-none shadow-sm ${
                              isNight 
                                ? 'bg-stone-800 border-stone-700 text-stone-200 placeholder-stone-600 focus:border-stone-500' 
                                : 'bg-white border-stone-300 text-stone-700 placeholder-stone-400 focus:border-nature-500'
                            }`}
                        />
                        <button 
                            onClick={() => processDecision(customAction)}
                            disabled={!customAction.trim()}
                            className="bg-stone-800 text-white px-6 rounded-xl font-semibold shadow-md hover:bg-stone-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                        >
                            Act
                        </button>
                    </div>
                 </div>
               </>
             )}
          </div>
        </div>

        {/* Bottom Chat */}
        <div className={`h-64 shrink-0 border-t z-20 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.1)] ${isNight ? 'bg-stone-900 border-stone-800' : 'bg-white border-stone-200'}`}>
            <ChatPanel context={gameState.currentScenario?.description || ""} />
        </div>
      </div>

      {/* Right Sidebar: Map & Score */}
      <div className={`hidden md:flex w-[380px] flex-col border-l relative ${isNight ? 'bg-stone-900 border-stone-800' : 'bg-stone-100 border-stone-200'}`}>
         <div className="flex-1 relative">
            <MapPanel scenario={gameState.currentScenario} />
         </div>
         <div className="p-4 shrink-0">
             <ScoreBoard scores={gameState.scores} theme={gameState.currentScenario?.theme || 'normal'} />
         </div>
      </div>
    </div>
  );
};
